version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/raspberry_pi
hooks:
  ApplicationStart:
    - location: scripts/start_script
      timeout: 100
  ApplicationStop:
    - location: scripts/stop_script
      timeout: 100
