#!/bin/bash

echo start_script start >> /home/ec2-user/raspberry_pi.log

python3 /home/ec2-user/raspberry_pi/main.py

file_name=/home/ec2-user/writed_main.txt

if [ -f ${file_name} ]; then
echo scp start >> /home/ec2-user/raspberry_pi.log
expect <<EOF
        spawn scp -o StrictHostKeyChecking=no -P 8001 -r /home/ec2-user/raspberry_pi pi@123.108.166.38:/home/pi/
        expect "password:"
        send "raspberry\r";
        expect eof
EOF

echo scp done >> /home/ec2-user/raspberry_pi.log
echo ssh start >> /home/ec2-user/raspberry_pi.log

expect <<EOF
        spawn ssh pi@123.108.166.38 -p 8001 python3 /home/pi/raspberry_pi/insert_search.py
        expect "password:"
        send "raspberry\r";
        expect eof
EOF

echo ssh done >> /home/ec2-user/raspberry_pi.log

else
        echo file not exist >> /home/ec2-user/raspberry_pi.log
fi
